### ISSUE TITLE
 Only SecretKey is supported

### ISSUE THREAD

**Issue by ornolisvt** [smstuebe/xamarin-fingerprint#174]
I encountered a bug in Firebase Crashlytics showing the fingerprint input dialog

## Steps to reproduce
I don`t know how to reproduce

## Expected behavior
Show the fingerprint dialog

## Actual behavior
Crash on show fingerprint dialog

### Crashlog
Fatal Exception: java.lang.RuntimeException: Failed to init Cipher at md5f842b5ac8eb52ac6d95c95091b13caff.FingerprintDialogFragment.n_onResume(FingerprintDialogFragment.java) at md5f842b5ac8eb52ac6d95c95091b13caff.FingerprintDialogFragment.onResume(FingerprintDialogFragment.java:44)
       at android.app.Fragment.performResume(Fragment.java:2554)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1562)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1623)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2994)
       at android.app.FragmentController.dispatchResume(FragmentController.java:200)
       at android.app.Activity.performResume(Activity.java:7227)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
Caused by java.security.InvalidKeyException: Only SecretKey is supported
       at com.android.org.conscrypt.OpenSSLCipher.checkAndSetEncodedKey(OpenSSLCipher.java:436)
       at com.android.org.conscrypt.OpenSSLCipher.engineInit(OpenSSLCipher.java:261)
       at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2668)
       at javax.crypto.Cipher.tryCombinations(Cipher.java:2575)
       at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2480)
       at javax.crypto.Cipher.chooseProvider(Cipher.java:567)
       at javax.crypto.Cipher.init(Cipher.java:831)
       at javax.crypto.Cipher.init(Cipher.java:772)
       at md5f842b5ac8eb52ac6d95c95091b13caff.FingerprintDialogFragment.n_onResume(FingerprintDialogFragment.java)
       at md5f842b5ac8eb52ac6d95c95091b13caff.FingerprintDialogFragment.onResume(FingerprintDialogFragment.java:44)
       at android.app.Fragment.performResume(Fragment.java:2554)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1562)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1623)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2994)
       at android.app.FragmentController.dispatchResume(FragmentController.java:200)
       at android.app.Activity.performResume(Activity.java:7227)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

## Configuration

**Version of the Plugin:** 1.4.9

**Platform:** Android 8.0

**Device:** Xiaomi Mi Max 3 (It only happens on that device according to the log)

**Comment by smsissuechecker** [comment]
Hi @ornolisvt,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
