### ISSUE TITLE
AllowAlternativeAuthentication + Samsung SM-M307FN quit app

### ISSUE THREAD

**Issue by matteopiccioni** [smstuebe/xamarin-fingerprint#193]
## Steps to reproduce

Hello, I have a Samsung SM-M307FN (Android 10) with finger id and face id enabled.
Using Plugin.Fingerprint 2.1.1, Xamarin Form 4.8.0.1451

If I use AllowAlternativeAuthentication=true then the app shows me the authentication popup (with finger and code option) and the app crashes at
`            var result = await CrossFingerprint.Current.AuthenticateAsync(dialogConfig);
`

If I use AllowAlternativeAuthentication = false then the app works in the right way and show me the authentication popup (with finger and face option).

## Expected behavior
The app should works with AllowAlternativeAuthentication = true

## Actual behavior
The app crashes

### Crashlog
Using logcat
`Errore (4601) / BiometricService: RemoteException
Errore (4601) / BiometricService: android.os.DeadObjectException
Errore (4601) / BiometricService: 	at android.os.BinderProxy.transactNative(Native Method)
Errore (4601) / BiometricService: 	at android.os.BinderProxy.transact(BinderProxy.java:527)
Errore (4601) / BiometricService: 	at android.hardware.biometrics.IBiometricServiceReceiver$Stub$Proxy.onAuthenticationSucceeded(IBiometricServiceReceiver.java:211)
Errore (4601) / BiometricService: 	at com.android.server.biometrics.BiometricService.handleOnConfirmDeviceCredentialSuccess(BiometricService.java:1618)
Errore (4601) / BiometricService: 	at com.android.server.biometrics.BiometricService.access$1300(BiometricService.java:99)
Errore (4601) / BiometricService: 	at com.android.server.biometrics.BiometricService$1.handleMessage(BiometricService.java:488)
Errore (4601) / BiometricService: 	at android.os.Handler.dispatchMessage(Handler.java:107)
Errore (4601) / BiometricService: 	at android.os.Looper.loop(Looper.java:237)
Errore (4601) / BiometricService: 	at com.android.server.SystemServer.run(SystemServer.java:929)
Errore (4601) / BiometricService: 	at com.android.server.SystemServer.main(SystemServer.java:723)
Errore (4601) / BiometricService: 	at java.lang.reflect.Method.invoke(Native Method)
Errore (4601) / BiometricService: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
Errore (4601) / BiometricService: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1046)
`

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin: 
Plugin.Fingerprint 2.1.1, Xamarin Form 4.8.0.1451

**Platform:**  
Android 10

**Device:**  
Samsung SM-M307FN

**Comment by smsissuechecker** [comment]
Hi @matteopiccioni,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.
