### ISSUE TITLE
.NET MAUI iOS crashes with "This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

### ISSUE THREAD

**Issue by people-hangover** [smstuebe/xamarin-fingerprint#243]
#Using Plugin.Fingerprint 2.1.5 on iOS  issue

> using Plugin.Fingerprint version 2.1.5 on iOS results in "This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

## Steps to reproduce

1. Download Plugin.Fingerprint version 2.1.5

2. Run the project on iOS simulator

3. Use biometric library

## Expected behavior
The biometrics property should initialize properly on iOS simulator

## Actual behavior
An exception is thrown:"This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

### Crashlog
System.AggregateException: One or more errors occurred. (This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.)
 ---> System.NotImplementedException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
   at Plugin.Fingerprint.CrossFingerprint.CreateFingerprint()
   at System.Lazy`1[[Plugin.Fingerprint.Abstractions.IFingerprint, Plugin.Fingerprint, Version=2.1.5.0, Culture=neutral, PublicKeyToken=null]].PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Lazy`1[[Plugin.Fingerprint.Abstractions.IFingerprint, Plugin.Fingerprint, Version=2.1.5.0, Culture=neutral, PublicKeyToken=null]].CreateValue()
   at System.Lazy`1[[Plugin.Fingerprint.Abstractions.IFingerprint, Plugin.Fingerprint, Version=2.1.5.0, Culture=neutral, PublicKeyToken=null]].get_Value()
   at Plugin.Fingerprint.CrossFingerprint.get_Current()
   at MauiApp.Helpers.BiometricHelper.IsBiometricsAvailableAsync() in /Documents/src/MauiApp/Helpers/BiometricHelper.cs:line 56

## Configuration

**Version of the Plugin:** 2.1.5

**Platform:** iOS

**Device:** iPhone 15 simulator, iphone 16 simulator

##Additional informaiton
-All necessary permissions are included in Info.plist
-package is properly referenced in the main project
-works fine on android withe the same implementation

##critical business impact
-unable to use beta versions(3.0.0-beta.1) due to company security policies and restrictions

**Comment by smsissuechecker** [comment]
Hi @people-hangover,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by NickTaplin** [comment]
Would be good to get an answer for this, I have been able to produce the error as well on an iPhone Xs running iOS 17.7.1, with the same version of the library.

**Comment by NickTaplin** [comment]
Have a possible fix you can try @people-hangover if you haven't already, using the 3.0.0-beta.1 build may resolve your issues, it did for us. Have to provide more details if you need.

**Comment by mfranc28** [comment]
Yes, with beta build it's works

**Comment by jvillaro** [comment]
I was getting the same error and tried v3.0.0-beta.1 as reccomended above and it works now. Is there a timeline for when i will come out of beta?
