### ISSUE TITLE
When i integrate fingerprint in my project , i got "ResolveLibraryProjectImports" task failed unexpectedly

### ISSUE THREAD

**Issue by sunilyts** [smstuebe/xamarin-fingerprint#54]
Hi ,

I am integrating finger print in my project but i got below error (detail error log~~~~).

Error The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'QuickJobSearch, Version=, Culture=neutral, PublicKeyToken='.
Perhaps it doesn't exist in the Mono for Android profile?
File name: 'yyyy~~~~.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters

parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection1 jars, ICollection1

resolvedResourceDirectories, ICollection1 resolvedAssetDirectories, ICollection1 resolvedEnvironments)
at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() QuickJobSearch.Droid

Please help me out.

Thanks,
Sunil Rana

To help us fix your issue, please provide the information in the below template. If something causes a crash, provide as much information as you can gather.
Just imagine: we do not know what you are doing! 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.

## Steps to reproduce

1.

2.

3.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

### Crashlog

If something causes an exception paste full stack trace + Exception here

## Configuration

**Version of the Plugin:** e.g. 1.0.0 / 1.0.1-alpha3

**Platform:** e.g. iOS 10.1 / Android 4.4 / ... (including version!!! e.g. Android 5.1 / i0S 10)

**Device:** e.g. HTC Sensation /i Phone 7 ...

**Comment by smsissuechecker** [comment]
Hi @sunilyts,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment]
Don't see any relation to my Plugin. Please fill out the template correctly and provide more infromation

**Comment by sunilyts** [comment]
Thank you for your response.

below is details for my issue.

Steps to reproduce

 1. Added finger print code in my application
var result = await Plugin.Fingerprint.CrossFingerprint.Current.AuthenticateAsync("Prove you have fingers!", _cancel.Token);

2. Added "Plugin.Fingerprint" for portable and droid project
3. Added "Plugin.Fingerprint" for  droid project 
4. Then i compile project and got Error The "ResolveLibraryProjectImports" task failed unexpectedly.



Expected behavior

**It should work properly without above error.**

Tell us what should happen

**I got Error The "ResolveLibraryProjectImports" task failed unexpectedly**

Actual behavior

**It should not give error above.**

Tell us what happens instead
****"Crashlog** "**

System.IO.FileNotFoundException: Could not load assembly 'QuickJobSearch, Version=, Culture=neutral, PublicKeyToken='.
Perhaps it doesn't exist in the Mono for Android profile?
File name: 'yyyy~~~~.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters

parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection1 jars, ICollection1

resolvedResourceDirectories, ICollection1 resolvedAssetDirectories, ICollection1 resolvedEnvironments)
at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() QuickJobSearch.Droid
If something causes an exception paste full stack trace + Exception here
Configuration

Version of the Plugin: e.g. 1.4.3 for fingerprint

Platform: e.g. Android 6.0   and xamarin studio version 4.2
Device: e.g. nexus 5.

Hope it will be helpful to you. Let me know if you need more details.

With Regards,
Sunil Rana

**Comment by smstuebe** [comment]
I still don't see any Problem related to the Plugin.

> System.IO.FileNotFoundException: Could not load assembly 'QuickJobSearch, Version=, Culture=neutral, PublicKeyToken='.
Perhaps it doesn't exist in the Mono for Android profile?
File name: 'yyyy~~~~.dll'

looks very weird.

**Comment by sunilyts** [comment]
It's Xamarin issue and i  updated Xamatin.VS 4.4  and it resolved my error .

Thank you for response.

Sincerely, 
Sunil Rana
